def test_cython_connect(n: int) -> None: ...

class VirtualMachine:
    poolsize: int
    def __init__(self, poolsize: int) -> None: ...
    def __del__(self) -> None: ...
    def reset(self) -> None: ...
    def run(self) -> int: ...
